import json
import os
from typing import Any, Dict, List

import streamlit as st


OUTPUTS_BASE = os.path.join(os.path.dirname(os.path.dirname(__file__)), "outputs", "accounts")
CHANGELOG_BASE = os.path.join(os.path.dirname(os.path.dirname(__file__)), "changelog")


def list_accounts(base: str) -> List[str]:
    if not os.path.isdir(base):
        return []
    return sorted(
        name for name in os.listdir(base)
        if os.path.isdir(os.path.join(base, name))
    )


def load_json(path: str) -> Dict[str, Any]:
    if not os.path.exists(path):
        return {}
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def main() -> None:
    st.set_page_config(page_title="Clara Account Viewer", layout="wide")
    st.title("Clara Zero-Cost Pipeline Dashboard")

    st.markdown(
        "Use this dashboard to browse accounts, compare `v1` and `v2` memos, "
        "inspect agent specs, and review changelogs generated by the pipelines."
    )

    accounts = list_accounts(OUTPUTS_BASE)
    if not accounts:
        st.warning("No accounts found under `outputs/accounts`. Run the demo and onboarding pipelines first.")
        return

    selected_account = st.sidebar.selectbox("Select account", accounts)

    v1_dir = os.path.join(OUTPUTS_BASE, selected_account, "v1")
    v2_dir = os.path.join(OUTPUTS_BASE, selected_account, "v2")

    v1_memo = load_json(os.path.join(v1_dir, "memo.json"))
    v2_memo = load_json(os.path.join(v2_dir, "memo.json"))

    v1_spec = load_json(os.path.join(v1_dir, "agent_spec.json"))
    v2_spec = load_json(os.path.join(v2_dir, "agent_spec.json"))

    changelog_md_path = os.path.join(CHANGELOG_BASE, f"{selected_account}.md")
    changelog_md = ""
    if os.path.exists(changelog_md_path):
        with open(changelog_md_path, "r", encoding="utf-8") as f:
            changelog_md = f.read()

    col1, col2 = st.columns(2)

    with col1:
        st.subheader("v1 Memo")
        st.json(v1_memo or {"info": "No v1 memo.json found."})
        st.subheader("v1 Agent Spec")
        st.json(v1_spec or {"info": "No v1 agent_spec.json found."})

    with col2:
        st.subheader("v2 Memo")
        st.json(v2_memo or {"info": "No v2 memo.json found."})
        st.subheader("v2 Agent Spec")
        st.json(v2_spec or {"info": "No v2 agent_spec.json found."})

    st.markdown("---")
    st.subheader("Changelog")
    if changelog_md:
        st.markdown(changelog_md)
    else:
        st.info("No changelog found for this account yet.")


if __name__ == "__main__":
    main()

